id: P8D11A060
initial_creation_type: ocr
source_metadata:
  volumes:
    8870ca5e95b4408880931a6565af545c:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཕྱག་འཚལ་བའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
